// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJb4TJZIax0CNcCZwb7ox27_yYQhXQFrw',
    appId: '1:936173877697:web:966fc2ba45ddf04994d740',
    messagingSenderId: '936173877697',
    projectId: 'balanco-c0b06',
    authDomain: 'balanco-c0b06.firebaseapp.com',
    storageBucket: 'balanco-c0b06.firebasestorage.app',
    measurementId: 'G-4QT6NVM0MT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA38gRqPdQv_uibHt2rm9FnuqP5eHDYiDE',
    appId: '1:936173877697:android:460c9ce4444d08bd94d740',
    messagingSenderId: '936173877697',
    projectId: 'balanco-c0b06',
    storageBucket: 'balanco-c0b06.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFC6xLEi36UtbpEDbtKeCpxXOrbmFkRZc',
    appId: '1:936173877697:ios:e728480b31be887394d740',
    messagingSenderId: '936173877697',
    projectId: 'balanco-c0b06',
    storageBucket: 'balanco-c0b06.firebasestorage.app',
    iosBundleId: 'com.balanco.balanco',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFC6xLEi36UtbpEDbtKeCpxXOrbmFkRZc',
    appId: '1:936173877697:ios:e728480b31be887394d740',
    messagingSenderId: '936173877697',
    projectId: 'balanco-c0b06',
    storageBucket: 'balanco-c0b06.firebasestorage.app',
    iosBundleId: 'com.balanco.balanco',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJb4TJZIax0CNcCZwb7ox27_yYQhXQFrw',
    appId: '1:936173877697:web:3f04a3ff1e665b7894d740',
    messagingSenderId: '936173877697',
    projectId: 'balanco-c0b06',
    authDomain: 'balanco-c0b06.firebaseapp.com',
    storageBucket: 'balanco-c0b06.firebasestorage.app',
    measurementId: 'G-46FST39ZS1',
  );
}
